service: sillycat-java-api

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  
package:
  artifact: target/sillycat-lambda-java-api-1.0.jar

functions:
  article-post:
    handler: com.sillycat.lambda.handler.ArticlePostHandler
    events:
      - http:
          path: articles
          method: POST
  article-get:
    handler: com.sillycat.lambda.handler.ArticleGetHandler
    events:
      - http:
          path: articles/{id}
          method: GET
          private: false
          request: 
            parameters: 
              paths: 
                id: true