service: sillycat-java-api

provider:
  name: aws
  runtime: java8
  
package:
  artifact: target/sillycat-lambda-java.jar

functions:
  echo:
    handler: com.sillycat.lambda.EchoHandler
    events:
      - http:
          path: echo
          method: get