service: sillycatapi

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    echo:
        handler: src/EchoHandler.php
        description: ''
        layers:
            - ${bref:layer.php-74}
    create-article:
        handler: src/CreateArticleHandler.php
        layers:
            - ${bref:layer.php-74}
        events:
            - httpApi: 'POST /articles'
    get-article:
        handler: src/GetArticleHandler.php
        layers:
            - ${bref:layer.php-74}
        events:
            - httpApi: 'GET /articles/{id}'

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
